[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from Palindrome
[ RUN      ] Palindrome.HandlesEmptyString
[       OK ] Palindrome.HandlesEmptyString (6 ms)
[ RUN      ] Palindrome.HandlesSingletons
[       OK ] Palindrome.HandlesSingletons (1 ms)
[ RUN      ] Palindrome.HandlesLengthTwo
[       OK ] Palindrome.HandlesLengthTwo (1 ms)
[ RUN      ] Palindrome.HandlesLengthThree
[       OK ] Palindrome.HandlesLengthThree (1 ms)
[ RUN      ] Palindrome.HandlesLengthFour
[       OK ] Palindrome.HandlesLengthFour (1 ms)
[ RUN      ] Palindrome.HandlesLongerStrings
[       OK ] Palindrome.HandlesLongerStrings (1 ms)
[----------] 6 tests from Palindrome (15 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (37 ms total)
[  PASSED  ] 6 tests.
==3818== Memcheck, a memory error detector
==3818== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3818== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==3818== Command: ./palindrome_test
==3818== 
==3818== 
==3818== HEAP SUMMARY:
==3818==     in use at exit: 264 bytes in 50 blocks
==3818==   total heap usage: 270 allocs, 220 frees, 123,282 bytes allocated
==3818== 
==3818== 1 bytes in 1 blocks are definitely lost in loss record 1 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015C9: Palindrome_HandlesEmptyString_Test::TestBody() (palindrome_test.cpp:14)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 2 bytes in 1 blocks are definitely lost in loss record 2 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015E3: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:18)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 2 bytes in 1 blocks are definitely lost in loss record 3 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015ED: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:19)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 2 bytes in 1 blocks are definitely lost in loss record 4 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015F7: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:20)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 5 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401611: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:24)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 6 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x40161B: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:25)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 7 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401625: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:26)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 8 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401625: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:26)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 9 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401653: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:32)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 10 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40165D: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:33)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 11 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40168B: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:39)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 12 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401695: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:40)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 13 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40169F: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:41)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 14 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016A9: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:42)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 15 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016EB: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:50)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 16 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016F5: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:51)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 17 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016FF: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:52)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 3 bytes in 1 blocks are definitely lost in loss record 18 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x4024AC: palindrome(char*) (palindrome.c:43)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401709: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:53)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 19 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015C9: Palindrome_HandlesEmptyString_Test::TestBody() (palindrome_test.cpp:14)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 20 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015E3: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:18)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 21 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015ED: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:19)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 22 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4015F7: Palindrome_HandlesSingletons_Test::TestBody() (palindrome_test.cpp:20)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 23 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401611: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:24)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 24 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x40161B: Palindrome_HandlesLengthTwo_Test::TestBody() (palindrome_test.cpp:25)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 25 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x40163F: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:30)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 26 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x40163F: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:30)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 27 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401649: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:31)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 28 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401649: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:31)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 29 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401653: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:32)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 30 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40165D: Palindrome_HandlesLengthThree_Test::TestBody() (palindrome_test.cpp:33)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 31 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401677: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:37)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 32 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401681: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:38)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 33 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016C3: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:46)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 34 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016CD: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:47)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 35 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016D7: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:48)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 4 bytes in 1 blocks are definitely lost in loss record 36 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x40246F: palindrome(char*) (palindrome.c:37)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016E1: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:49)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x401A77: RUN_ALL_TESTS() (gtest.h:2288)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 37 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401677: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:37)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 38 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x401681: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:38)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 39 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40168B: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:39)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 40 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401695: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:40)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 41 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x40169F: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:41)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 5 bytes in 1 blocks are definitely lost in loss record 42 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016A9: Palindrome_HandlesLengthFour_Test::TestBody() (palindrome_test.cpp:42)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 12 bytes in 1 blocks are definitely lost in loss record 43 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016C3: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:46)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 12 bytes in 1 blocks are definitely lost in loss record 44 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016EB: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:50)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 13 bytes in 1 blocks are definitely lost in loss record 45 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016CD: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:47)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 14 bytes in 1 blocks are definitely lost in loss record 46 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016D7: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:48)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 14 bytes in 1 blocks are definitely lost in loss record 47 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016FF: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:52)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 15 bytes in 1 blocks are definitely lost in loss record 48 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4013AE: is_palindrome(char*) (palindrome_test.cpp:6)
==3818==    by 0x4016E1: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:49)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 15 bytes in 1 blocks are definitely lost in loss record 49 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x401709: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:53)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== 18 bytes in 1 blocks are definitely lost in loss record 50 of 50
==3818==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==3818==    by 0x402392: str_reverse(char*) (palindrome.c:12)
==3818==    by 0x402402: palindrome(char*) (palindrome.c:27)
==3818==    by 0x4014BD: not_palindrome(char*) (palindrome_test.cpp:10)
==3818==    by 0x4016F5: Palindrome_HandlesLongerStrings_Test::TestBody() (palindrome_test.cpp:51)
==3818==    by 0x4E74533: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C3F9: testing::Test::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C547: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C624: testing::TestCase::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6C8F6: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E749E3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /usr/lib64/libgtest.so.0.0.0)
==3818==    by 0x4E6CBFF: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.0.0.0)
==3818== 
==3818== LEAK SUMMARY:
==3818==    definitely lost: 264 bytes in 50 blocks
==3818==    indirectly lost: 0 bytes in 0 blocks
==3818==      possibly lost: 0 bytes in 0 blocks
==3818==    still reachable: 0 bytes in 0 blocks
==3818==         suppressed: 0 bytes in 0 blocks
==3818== 
==3818== For counts of detected and suppressed errors, rerun with: -v
==3818== ERROR SUMMARY: 50 errors from 50 contexts (suppressed: 0 from 0)
